platform:
  - x86
  - x64

environment:
  matrix:
  # Add here environement variables to control the Travis CI build
    - CONDA_RECIPE: boost
      CONDA_VERSION: 2

    - CONDA_RECIPE: qhull
      CONDA_VERSION: 2

    - CONDA_RECIPE: ann
      CONDA_VERSION: 2

    - CONDA_RECIPE: eigen
      CONDA_VERSION: 2

  #  - CONDA_RECIPE: cgal
  #    CONDA_VERSION: 2

    - CONDA_RECIPE: deploy
      CONDA_VERSION: 2

    - CONDA_RECIPE: scons
      CONDA_VERSION: 2

    - CONDA_RECIPE: sconsx
      CONDA_VERSION: 2

    - CONDA_RECIPE: openalea.core
      CONDA_VERSION: 2

    - CONDA_RECIPE: openalea.vpltk
      CONDA_VERSION: 2

    - CONDA_RECIPE: openalea.grapheditor
      CONDA_VERSION: 2

    - CONDA_RECIPE: openalea.visualea
      CONDA_VERSION: 2

    - CONDA_RECIPE: plantgl
      CONDA_VERSION: 2

    - CONDA_RECIPE: lpy
      CONDA_VERSION: 2

    - CONDA_RECIPE: openalea.oalab
      CONDA_VERSION: 2

    - CONDA_RECIPE: mtg
      CONDA_VERSION: 2

    - ANACONDA_RELEASE: true

install:
  - git clone https://github.com/OpenAlea/appveyor-ci.git appveyor-ci
  - cd appveyor-ci
  - call install.bat

before_build:
  - call before_build.bat

build_script:
  - call build_script.bat

after_build:
  - call after_build.bat

deploy:
  provider: Script
  on:
    branch: master

before_deploy:
  - call before_deploy.bat

deploy_script:
  - call deploy_script.bat

after_deploy:
  - call after_deploy.bat

on_success:
  - call on_success.bat

on_failure:
  - call on_failure.bat

on_finish:
  - call on_finish.bat
